(4, 1, 'E1', 'support-1@techk-nots.com', 'Urgent action required for Team 1. Click here to secure your account.', 'PHISHING', false),
(5, 1, 'E2', 'hr@techknots.in', 'Team 1, here is the updated policy document for this quarter. No action needed.', 'GENUINE', false),
(6, 1, 'E3', 'alert-1@security-notify.com', 'New login detected on Team 1 dashboard. Verify identity immediately.', 'PHISHING', false),
(7, 2, 'E1', 'support-2@techk-nots.com', 'Urgent action required for Team 2. Click here to secure your account.', 'PHISHING', false),
(8, 2, 'E2', 'hr@techknots.in', 'Team 2, here is the updated policy document for this quarter. No action needed.', 'GENUINE', false),
(9, 2, 'E3', 'alert-2@security-notify.com', 'New login detected on Team 2 dashboard. Verify identity immediately.', 'PHISHING', false),
(10, 3, 'E1', 'support-3@techk-nots.com', 'Urgent action required for Team 3. Click here to secure your account.', 'PHISHING', false),
(11, 3, 'E2', 'hr@techknots.in', 'Team 3, here is the updated policy document for this quarter. No action needed.', 'GENUINE', false),
(12, 3, 'E3', 'alert-3@security-notify.com', 'New login detected on Team 3 dashboard. Verify identity immediately.', 'PHISHING', false),
(13, 4, 'E1', 'support-4@techk-nots.com', 'Urgent action required for Team 4. Click here to secure your account.', 'PHISHING', false),
(14, 4, 'E2', 'hr@techknots.in', 'Team 4, here is the updated policy document for this quarter. No action needed.', 'GENUINE', false),
(15, 4, 'E3', 'alert-4@security-notify.com', 'New login detected on Team 4 dashboard. Verify identity immediately.', 'PHISHING', false),
(16, 5, 'E1', 'support-5@techk-nots.com', 'Urgent action required for Team 5. Click here to secure your account.', 'PHISHING', false),
(17, 5, 'E2', 'hr@techknots.in', 'Team 5, here is the updated policy document for this quarter. No action needed.', 'GENUINE', false),
(18, 5, 'E3', 'alert-5@security-notify.com', 'New login detected on Team 5 dashboard. Verify identity immediately.', 'PHISHING', false),
(19, 6, 'E1', 'support-6@techk-nots.com', 'Urgent action required for Team 6. Click here to secure your account.', 'PHISHING', false),
(20, 6, 'E2', 'hr@techknots.in', 'Team 6, here is the updated policy document for this quarter. No action needed.', 'GENUINE', false),
(21, 6, 'E3', 'alert-6@security-notify.com', 'New login detected on Team 6 dashboard. Verify identity immediately.', 'PHISHING', false),
(22, 7, 'E1', 'support-7@techk-nots.com', 'Urgent action required for Team 7. Click here to secure your account.', 'PHISHING', false),
(23, 7, 'E2', 'hr@techknots.in', 'Team 7, here is the updated policy document for this quarter. No action needed.', 'GENUINE', false),
(24, 7, 'E3', 'alert-7@security-notify.com', 'New login detected on Team 7 dashboard. Verify identity immediately.', 'PHISHING', false),
(25, 8, 'E1', 'support-8@techk-nots.com', 'Urgent action required for Team 8. Click here to secure your account.', 'PHISHING', false),
(26, 8, 'E2', 'hr@techknots.in', 'Team 8, here is the updated policy document for this quarter. No action needed.', 'GENUINE', false),
(27, 8, 'E3', 'alert-8@security-notify.com', 'New login detected on Team 8 dashboard. Verify identity immediately.', 'PHISHING', false),
(28, 9, 'E1', 'support-9@techk-nots.com', 'Urgent action required for Team 9. Click here to secure your account.', 'PHISHING', false),
(29, 9, 'E2', 'hr@techknots.in', 'Team 9, here is the updated policy document for this quarter. No action needed.', 'GENUINE', false),
(30, 9, 'E3', 'alert-9@security-notify.com', 'New login detected on Team 9 dashboard. Verify identity immediately.', 'PHISHING', false),
(31, 10, 'E1', 'support-10@techk-nots.com', 'Urgent action required for Team 10. Click here to secure your account.', 'PHISHING', false),
(32, 10, 'E2', 'hr@techknots.in', 'Team 10, here is the updated policy document for this quarter. No action needed.', 'GENUINE', false),
(33, 10, 'E3', 'alert-10@security-notify.com', 'New login detected on Team 10 dashboard. Verify identity immediately.', 'PHISHING', false),
(34, 11, 'E1', 'support-11@techk-nots.com', 'Urgent action required for Team 11. Click here to secure your account.', 'PHISHING', false),
(35, 11, 'E2', 'hr@techknots.in', 'Team 11, here is the updated policy document for this quarter. No action needed.', 'GENUINE', false),
(36, 11, 'E3', 'alert-11@security-notify.com', 'New login detected on Team 11 dashboard. Verify identity immediately.', 'PHISHING', false),
(37, 12, 'E1', 'support-12@techk-nots.com', 'Urgent action required for Team 12. Click here to secure your account.', 'PHISHING', false),
(38, 12, 'E2', 'hr@techknots.in', 'Team 12, here is the updated policy document for this quarter. No action needed.', 'GENUINE', false),
(39, 12, 'E3', 'alert-12@security-notify.com', 'New login detected on Team 12 dashboard. Verify identity immediately.', 'PHISHING', false);